### ISSUE TITLE
Grails databinding configuration from mdm-core does not apply in mdm-application-build

### ISSUE THREAD

**Issue by joe-crawford** [MauroDataMapper/mdm-application-build#8]
The following configuration from the plugin.yml files in mdm-core does not take effect in mdm-application-build. When importing some DataModels errors can occur such as `reportDate cannot be null` when the imported date does not match the expected format. Also affects mdm-docker.

```yaml
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SXXX"
            - "yyyy-MM-dd'T'HH:mm:ssXXX"
            - 'yyyy-MM-dd HH:mm:ss.S'
            - "yyyy-MM-dd'T'HH:mm:ss'Z'"
            - "yyyy-MM-dd HH:mm:ss.S z"
            - "yyyy-MM-dd"
```

Likely related to https://github.com/grails/grails-core/issues/11767.
